Repository cloudeteer/m365-exporter, pull requests merged in 2025-02, with the labels that each got.

#14 OE-209: add intune os metrics
  .golangci.yaml
  docs/collector.intune.md
  pkg/collectors/intune/intune.go
  pkg/collectors/intune/intune_test.go
Labels: ✨ enhancement

#18 chore: fix codecov
  .codecov.yml
Labels: chore

#19 OE-212: add user metrics
  cmd/m365-exporter/main.go
  docs/collector.entraid.md
  go.mod
  pkg/collectors/entraid/entraid.go
  pkg/collectors/entraid/entraid_test.go
  pkg/collectors/entraid/entraid_test_test.go
Labels: ✨ enhancement

#21 add logo and center header
  README.md
  docs/sources/assets/logo_m365_exporter.svg
Labels: 📖 docs
